# Generated by Django 5.2.13 on 2026-07-14 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patient_guardian_contact_patient_user_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='guardian_contact',
            field=models.CharField(blank=True, help_text='Format: 254XXXXXXXXX (12 digits)', max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number starting with 254 followed by 9 digits (e.g. 254712345678).', regex='^254\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number starting with 254 followed by 9 digits (e.g. 254712345678).', regex='^254\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number starting with 254 followed by 9 digits (e.g. 254712345678).', regex='^254\\d{9}$')]),
        ),
    ]
