# Generated by Django 5.2.13 on 2026-07-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_patient_guardian_contact_alter_patient_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Force password change on next login (set for auto-generated accounts).'),
        ),
    ]
