# Generated by Django 5.2.13 on 2026-07-14 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_patients', models.BooleanField(default=True)),
                ('can_register_patients', models.BooleanField(default=True)),
                ('can_record_vaccination', models.BooleanField(default=True)),
                ('can_view_stock', models.BooleanField(default=True)),
                ('can_manage_stock', models.BooleanField(default=False)),
                ('can_view_batches', models.BooleanField(default=True)),
                ('can_manage_batches', models.BooleanField(default=False)),
                ('can_restock', models.BooleanField(default=True)),
                ('can_view_alerts', models.BooleanField(default=True)),
                ('can_resolve_alerts', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
