# Generated by Django 5.2.13 on 2026-05-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='next_vaccine_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='next_vaccine_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
